name: Remote Dispatch Action Initiator
on: 

    push:
    release:
      types: [created]
jobs:
  initiator:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2.1.0
      with:
        token: ${{ secrets.MY_ORG }}
        event-type: my-event
        repository: selftestdisco/TestRxJS
