name: Remote Dispatch Action Initiator
on: 
    release:
      types: 
        - published
        - unpublished
        - created
        - edited
        - deleted
jobs:
  initiator:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/selftestdisco/TestRxJS/.github/workflows/main.yml/dispatches
