name: Remote Dispatch Action Initiator
on: 
    #push:
    release:
      types: [created]
jobs:
  initiator:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
    - name: compare version
      run:   python3 --version
    - run: |
        cat << EOF >>compare.py
        import sys
        def versionCompare(v1, v2):
            arr1 = v1.split(".")
            arr2 = v2.split(".")
            n = len(arr1)
            m = len(arr2)
            # converts to integer from string
            arr1 = [int(i) for i in arr1]
            arr2 = [int(i) for i in arr2]
            # compares which list is bigger and fills
            # smaller list with zero (for unequal delimiters)
            if n>m:
                for i in range(m, n):
                    arr2.append(0)
            elif m>n:
                for i in range(n, m):
                    arr1.append(0)
            # returns 1 if version 1 is bigger and -1 if
            # version 2 is bigger and 0 if equal
            for i in range(len(arr1)):
                if arr1[i]>arr2[i]:
                    return 1
                elif arr2[i]>arr1[i]:
                    return -1
            return 0
        # Driver program to check above comparison function
        version1 = sys.argv[1]
        version2 = sys.argv[2]
        ans = versionCompare(version1, version2)
        if ans < 0:
            print ("Greater")
        elif ans > 0:
            print ("Smaller")
        else:
            print ("Equal")
        EOF
    - run: |
        curl -H 'Authorization: token ${{ secrets.MY_ORG }}' \
        -o /tmp/package.json \
        https://raw.githubusercontent.com/selftestdisco/TestRxJS/master/package.json
        
    - id: ans
      run: |
        
        export arg1=`cat /tmp/package.json |  grep '"version":' | sed -E 's/.*"([^"]+)".*/\1/'`
        echo $arg1
        export arg2="`curl -H 'Authorization: token ${{ secrets.MY_ORG }}' --silent "https://api.github.com/repos/selftestdisco/searchgitusers/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' `"
        echo $arg2
        python3 compare.py  $arg1 $arg2  > ans.txt
        cat ans.txt
        echo "test=`cat ans.txt`"  >> $GITHUB_OUTPUT
        
    - run: echo ${{ steps.ans.outputs.test }}
    
    - if: ${{ steps.ans.outputs.test == 'Greater' }}
      name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2.1.0
      with:
          token: ${{ secrets.MY_ORG }}
          event-type: my-event
          repository: selftestdisco/TestRxJS
    
