export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const SELECT_USER = "SELECT_USER";